Algoritmo "tabuada"
// Disciplina   :
// Professor   :
// Descrição   : tabuada
// Autor(a)    : Carlos e Gustavo
// Data atual  : 04/04/2023
Var
// Seção de Declarações das variáveis 
x,r:real
i:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("qual numero você quer fazer a tabuada?")
   leia (x)
   i:=1
   enquanto (i<=10) faca
   r:=x*i
   escreva(x,"x",i,"=",r)
   i:=i+1
   fimenquanto

Fimalgoritmo